// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rzyvsgcwntzoejtasvqa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6eXZzZ2N3bnR6b2VqdGFzdnFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5NjY4NjcsImV4cCI6MjA2MjU0Mjg2N30.SUPeKxDpI8Fs8IyZLyVYx6hyWstxKJT8ooH-kqTR9vE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);