// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emykkicieqkqfxiqrmdy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVteWtraWNpZXFrcWZ4aXFybWR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5NjU5MTEsImV4cCI6MjA2MjU0MTkxMX0.u19Lhyck9CC6rwoPv3RjSydWbIkCxBZhiXSAMYlwIrI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);